---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: aae
  namespace: aae
spec:
  gitImplementation: go-git
  interval: 1m0s
  ref:
    branch: opsexp-702
  secretRef:
    name: flux-system
  url: ssh://git@github.com/Alfresco/alfresco-process-infrastructure-deployment.git
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aae
  namespace: aae
spec:
  interval: 1m
  chart:
    spec:
      chart: /helm/alfresco-process-infrastructure/
      version: '7.1.0-M12'
      sourceRef:
        kind: HelmRepository
        name: aae
        namespace: aae
      interval: 1m
  valuesFrom:
  - kind: ConfigMap
    name: aae-values-configmap
    valuesKey: aae-values.yaml
